# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: gulu-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.19.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.19.0
      uses: actions/setup-node@v3
      with:
        node-version: '12.19.0'
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: sed '86c "./package.json":"./package.json"' ./node_modules/sinon/package.json
    - run: npx parcel build index.html --no-cache
    - run: npm test
